name: Setup Environment
description: 'Environment setup with caching'

inputs:
  ruby-version:
    description: 'Ruby version to install'
    required: false
    default: '3.3'
  enable-bundler-cache:
    description: 'Enable bundler cache'
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: 💎 Setup Ruby ${{ inputs.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler-cache: ${{ inputs.enable-bundler-cache }}
    
    - name: 🔧 Configure Bundle
      shell: bash
      run: |
        set -euo pipefail
        bundle config set --local deployment 'false'
        bundle config set --local jobs '4'
        bundle config set --local retry '3'