name: Setup Environment
description: 'Combined setup (Ruby, Node, cache) for gem-ci workflows'

inputs:
  ruby-version:
    description: 'Ruby version to install'
    required: false
    default: '3.3'
  node-version:
    description: 'Node.js version to install'
    required: false
    default: '20'
  enable-bundler-cache:
    description: 'Enable bundler cache'
    required: false
    default: 'true'
  enable-node-cache:
    description: 'Enable Node.js cache'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: 💎 Setup Ruby ${{ inputs.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler-cache: ${{ inputs.enable-bundler-cache }}
      
    - name: 📦 Setup Node.js ${{ inputs.node-version }}
      if: inputs.enable-node-cache == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
    
    - name: ✅ Display environment info
      shell: bash
      run: |
        set -euo pipefail
        echo "🔧 Environment Setup Complete"
        echo "Ruby: $(ruby --version)"
        echo "Bundler: $(bundle --version)"
        if command -v node >/dev/null 2>&1; then
          echo "Node: $(node --version)"
          echo "npm: $(npm --version)"
        fi