name: 🚀 Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["type: feature", "needs review"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! This helps us improve the project.

  - type: textarea
    id: feature-description
    attributes:
      label: 🚀 Feature Description
      description: A clear and concise description of the feature you'd like
      placeholder: Describe the feature you'd like to see...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: 🤔 Problem Statement
      description: What problem does this feature solve?
      placeholder: Explain the problem this feature would address...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: 💡 Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered
      description: Have you considered any alternative solutions?
      placeholder: Describe any alternative solutions you've considered...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: 📊 Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my workflow
        - Critical - Blocking my work
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: 🛠️ Implementation
      description: Are you willing to help implement this feature?
      options:
        - label: I'm willing to submit a PR for this feature
          required: false
        - label: I can provide additional details if needed
          required: false
        - label: I can help with testing
          required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Add any other context, screenshots, or examples
      placeholder: Any additional information that might be helpful...
    validations:
      required: false
