name: GitHub App Token
description: 'Generate GitHub App authentication token for personal branding'

inputs:
  app-id:
    description: 'GitHub App ID from secrets'
    required: true
  private-key:
    description: 'GitHub App private key from secrets'
    required: true

outputs:
  token:
    description: 'Generated GitHub App token'
    value: ${{ steps.app_token.outputs.token }}

runs:
  using: composite
  steps:
    - name: 🔑 Generate GitHub App Token
      id: app_token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}
    
    - name: ✅ Validate token
      shell: bash
      run: |
        set -euo pipefail
        if [ ${#TOKEN} -gt 0 ]; then
          echo "✅ GitHub App token generated (${#TOKEN} chars)"
        else
          echo "❌ Token generation failed"
          exit 1
        fi
      env:
        TOKEN: ${{ steps.app_token.outputs.token }}