# frozen_string_literal: true

source "https://rubygems.org"

# Jekyll and theme
gem "jekyll", "~> 4.3.0"
gem "jekyll-theme-cayman", "~> 0.2.0"

# Jekyll plugins
gem "jekyll-feed", "~> 0.12"
gem "jekyll-sitemap", "~> 1.4"
gem "jekyll-seo-tag", "~> 2.8"

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Lock `http_parser.rb` gem to `v0.6.x` on JRuby builds since newer versions of the gem
# do not have a Java counterpart.
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]

# GitHub Pages compatibility
gem "webrick", "~> 1.8"

# Fix Ruby 3.4.0 compatibility warnings
gem "csv", "~> 3.2"
gem "base64", "~> 0.1"