name: Run Tests
description: 'Test execution with coverage'

inputs:
  test-command:
    description: 'Test command to run'
    required: false
    default: 'bundle exec rspec'
  coverage-enabled:
    description: 'Enable coverage reporting'
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: 🧪 Run Tests
      shell: bash
      run: |
        set -euo pipefail
        
        echo "🧪 Running tests..."
        
        if [ "${{ inputs.coverage-enabled }}" == "true" ]; then
          export COVERAGE=true
        fi
        
        ${{ inputs.test-command }}
      env:
        COVERAGE: ${{ inputs.coverage-enabled }}
    
    - name: 📤 Upload Coverage
      if: inputs.coverage-enabled == 'true' && always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-${{ github.run_id }}
        path: coverage/
        if-no-files-found: warn